### ISSUE TITLE
Error processing tar file(exit status 1): write /usr/libexec/gcc/x86_64-alpine-linux-musl/6.4.0/lto1: no space left on device

### ISSUE THREAD

**Issue by SaintNazaire** [nardeas/tensorflow-syntaxnet#2]
- Windows 10 Pro
- Docker 17.12.0-ce-win47

Build error message as follow

> Step 7/40 : RUN apk --no-cache --update add --virtual .builddeps.bazel         bash         build-base         linux-headers         python         openjdk8         wget         zip
>  ---> Running in 995ca00b30c2
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
> (1/70) Upgrading musl (1.1.18-r2 -> 1.1.18-r3)
> (2/70) Installing pkgconf (1.3.10-r0)
> (3/70) Installing ncurses-terminfo-base (6.0_p20171125-r0)
> (4/70) Installing ncurses-terminfo (6.0_p20171125-r0)
> (5/70) Installing ncurses-libs (6.0_p20171125-r0)
> (6/70) Installing readline (7.0.003-r0)
> (7/70) Installing bash (4.4.19-r1)
> Executing bash-4.4.19-r1.post-install
> (8/70) Installing binutils-libs (2.28-r3)
> (9/70) Installing binutils (2.28-r3)
> (10/70) Installing gmp (6.1.2-r1)
> (11/70) Installing isl (0.18-r0)
> (12/70) Installing libgomp (6.4.0-r5)
> (13/70) Installing libatomic (6.4.0-r5)
> (14/70) Installing libgcc (6.4.0-r5)
> (15/70) Installing mpfr3 (3.1.5-r1)
> (16/70) Installing mpc1 (1.0.3-r1)
> (17/70) Installing libstdc++ (6.4.0-r5)
> (18/70) Installing gcc (6.4.0-r5)
> (19/70) Installing musl-dev (1.1.18-r3)
> (20/70) Installing libc-dev (0.7.1-r0)
> (21/70) Installing g++ (6.4.0-r5)
> (22/70) Installing make (4.2.1-r0)
> (23/70) Installing fortify-headers (0.9-r0)
> (24/70) Installing build-base (0.5-r0)
> (25/70) Installing linux-headers (4.4.6-r2)
> (26/70) Installing libbz2 (1.0.6-r6)
> (27/70) Installing expat (2.2.5-r0)
> (28/70) Installing libffi (3.2.1-r4)
> (29/70) Installing gdbm (1.13-r1)
> (30/70) Installing sqlite-libs (3.21.0-r0)
> (31/70) Installing python2 (2.7.14-r2)
> (32/70) Installing libtasn1 (4.12-r2)
> (33/70) Installing p11-kit (0.23.2-r2)
> (34/70) Installing p11-kit-trust (0.23.2-r2)
> (35/70) Installing ca-certificates (20171114-r0)
> (36/70) Installing java-cacerts (1.0-r0)
> (37/70) Installing libxau (1.0.8-r2)
> (38/70) Installing libbsd (0.8.6-r1)
> (39/70) Installing libxdmcp (1.1.2-r4)
> (40/70) Installing libxcb (1.12-r1)
> (41/70) Installing libx11 (1.6.5-r1)
> (42/70) Installing libxcomposite (0.4.4-r1)
> (43/70) Installing libxext (1.3.3-r2)
> (44/70) Installing libxi (1.7.9-r1)
> (45/70) Installing libxrender (0.9.10-r2)
> (46/70) Installing libxtst (1.2.3-r1)
> (47/70) Installing alsa-lib (1.1.4.1-r2)
> (48/70) Installing libpng (1.6.34-r1)
> (49/70) Installing freetype (2.8.1-r2)
> (50/70) Installing giflib (5.1.4-r1)
> (51/70) Installing libjpeg-turbo (1.5.2-r0)
> (52/70) Installing openjdk8-jre-lib (8.151.12-r0)
> (53/70) Installing java-common (0.1-r0)
> (54/70) Installing krb5-conf (1.0-r1)
> (55/70) Installing libcom_err (1.43.7-r0)
> (56/70) Installing keyutils-libs (1.5.10-r0)
> (57/70) Installing libverto (0.3.0-r0)
> (58/70) Installing krb5-libs (1.15.2-r1)
> (59/70) Installing lcms2 (2.8-r1)
> (60/70) Installing nspr (4.17-r0)
> (61/70) Installing nss (3.34.1-r0)
> (62/70) Installing pcsc-lite-libs (1.8.22-r0)
> (63/70) Installing lksctp-tools (1.0.17-r0)
> (64/70) Installing openjdk8-jre-base (8.151.12-r0)
> (65/70) Installing openjdk8-jre (8.151.12-r0)
> (66/70) Installing openjdk8 (8.151.12-r0)
> (67/70) Installing wget (1.19.2-r1)
> (68/70) Installing zip (3.0-r4)
> (69/70) Installing .builddeps.bazel (0)
> (70/70) Upgrading musl-utils (1.1.18-r2 -> 1.1.18-r3)
> Executing busybox-1.27.2-r7.trigger
> Executing ca-certificates-20171114-r0.trigger
> Executing java-common-0.1-r0.trigger
> OK: 307 MiB in 79 packages
> Error processing tar file(exit status 1): write /usr/libexec/gcc/x86_64-alpine-linux-musl/6.4.0/lto1: no space left on device

**Comment by nardeas** [comment]
You're probably running out of disk space allocated for Docker, hence the `no space left on device` error. I would check my `Docker.qcow2` to see if it's approaching limits and perhaps remove some unused images

**Comment by nardeas** [comment]
For reference check this one https://github.com/docker/for-win/issues/1042
